import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination, Autoplay } from "swiper/modules";
import "./Welcome.scss";
import Welcome1 from "../../../assets/images/welcome1.svg";
const Welcome = () => {
    return (_jsx("section", { id: "welcome", children: _jsx("div", { className: "container", children: _jsxs(Swiper, { modules: [Pagination, Autoplay], pagination: { clickable: true }, autoplay: { delay: 4000 }, loop: true, spaceBetween: 50, slidesPerView: 1, children: [_jsx(SwiperSlide, { children: _jsxs("div", { className: "welcome", children: [_jsxs("div", { className: "welcome--title", children: [_jsx("h4", { children: "Welcome to GreenShop" }), _jsxs("h1", { children: ["Let\u2019s Make a Better ", _jsx("span", { children: "Planet" })] }), _jsx("p", { children: "We are an online plant shop offering a wide range of cheap and trendy plants. Use our plants to create an unique Urban Jungle. Order your favorite plants!" }), _jsx("button", { children: "SHOP NOW" })] }), _jsx("div", { className: "welcome--img", children: _jsx("img", { src: Welcome1, alt: "img" }) })] }) }), _jsx(SwiperSlide, { children: _jsxs("div", { className: "welcome", children: [_jsxs("div", { className: "welcome--title", children: [_jsx("h4", { children: "GreenShop Specials" }), _jsxs("h1", { children: ["Bring Nature To Your ", _jsx("span", { children: "Home" })] }), _jsx("p", { children: "Discover a variety of beautiful indoor and outdoor plants that refresh your space and improve your lifestyle." }), _jsx("button", { children: "DISCOVER" })] }), _jsx("div", { className: "welcome--img", children: _jsx("img", { src: Welcome1, alt: "img" }) })] }) }), _jsx(SwiperSlide, { children: _jsxs("div", { className: "welcome", children: [_jsxs("div", { className: "welcome--title", children: [_jsx("h4", { children: "Exclusive Offers" }), _jsxs("h1", { children: ["Make Your Life More ", _jsx("span", { children: "Green" })] }), _jsx("p", { children: "Choose from our best collections with exclusive discounts. Bring freshness and calmness to your space with beautiful plants." }), _jsx("button", { children: "EXPLORE" })] }), _jsx("div", { className: "welcome--img", children: _jsx("img", { src: Welcome1, alt: "img" }) })] }) })] }) }) }));
};
export default Welcome;
